#安装相关依赖库：
- plyfile用于读取ply文件
- plotly用于可视化点云
- autowrap是go-icp的依赖库

In [2]:
!pip install plyfile
!pip install plotly
!pip install autowrap

     |████████████████████████████████| 860kB 3.2MB/s 
  Created wheel for autowrap: filename=autowrap-0.22.0-cp36-none-any.whl size=2048845 sha256=d92476f0a49b142559362140ac334e8ca0ab78e09af8139cff80b1e5cd601990
  Stored in directory: /root/.cache/pip/wheels/fb/88/11/f59b94b8d24cafbdc2e39ce4adbee54e827df09de2f486c831
Successfully built autowrap


#安装go-icp

In [3]:
!git clone https://github.com/xvlinihao/go-icp_cython.git
%cd go-icp_cython/
!python setup.py install
%cd ..

Cloning into 'go-icp_cython'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 102 (delta 3), reused 11 (delta 1), pack-reused 88
Receiving objects: 100% (102/102), 1.86 MiB | 11.92 MiB/s, done.
Resolving deltas: 100% (38/38), done.
/content/go-icp_cython
FOUND AUTOWRAP LIBRARY, PROCEED
PRECOMPILE USING AUTOWRAP BEFORE PROCEEDING
Level 25:root:parsing progress 0 out of 1
INFO:root:start resolving decls
INFO:root:resolve_inheritance for POINT3D
INFO:root:resolve_inheritance for ROTNODE
INFO:root:resolve_inheritance for TRANSNODE
INFO:root:resolve_inheritance for GoICP
INFO:root:resolve class decl POINT3D
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void POINT3D ([])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void POINT3D (['float ', 'float ', 'float '])'
INFO:root:resolve method decl: 'CppMethodOrFunctionDecl: void pointToString ([])'
INFO:root:resolve class de

- **transform.py**的作用是对输入的源点云做刚体变化，产生其他视角的点云，
- **transform**.py支持两个参数：
> - **--data_sort**:输入的数据类型：支持ply或者npy格式的点云
> - **--src**:源点云的路劲

In [0]:
!python transform.py --data_sort=npy --src=b.npy

#对变化结果进行可视化
- 白色为输入数据

In [5]:
import numpy as np
import plotly.graph_objects as go
from plyfile import PlyData

#data=PlyData.read('bunny.ply')['vertex']
#a=np.c_[data['x'],data['y'],data['z']]
#读取ply文件的时候请取消注释


a=np.load('b.npy')
t1=np.load('transformed_data/1.npy')
t2=np.load('transformed_data/2.npy')
t3=np.load('transformed_data/3.npy')
t4=np.load('transformed_data/4.npy')
t5=np.load('transformed_data/5.npy')
t6=np.load('transformed_data/6.npy')
t7=np.load('transformed_data/7.npy')
t8=np.load('transformed_data/8.npy')


fig0=go.Figure(data=[go.Scatter3d(
        x=t1[:,0],
        y=t1[:,1],
        z=t1[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='red',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=t2[:,0],
        y=t2[:,1],
        z=t2[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='blue',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=t3[:,0],
        y=t3[:,1],
        z=t3[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='green',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=t4[:,0],
        y=t4[:,1],
        z=t4[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='yellow',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=t5[:,0],
        y=t5[:,1],
        z=t5[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='pink',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=t6[:,0],
        y=t6[:,1],
        z=t6[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='brown',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=t7[:,0],
        y=t7[:,1],
        z=t7[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='black',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=t8[:,0],
        y=t8[:,1],
        z=t8[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='purple',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=a[:,0],
        y=a[:,1],
        z=a[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='white',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    )
    ])
    #new_data = generate_dataset(origin_data)
fig0.update_layout(margin=dict(l=0, r=0, b=0, t=0))
fig0.show()

#利用神经网络进行粗配准，为精配准获得良好的初始位置

In [6]:
!python test.py --exp_name=dcp_v2 --model=dcp --emb_nn=pointnet --pointer=transformer --head=svd --eval --model_path=model.best.t7 --src=transformed_data/1.npy --target=transformed_data/2.npy --batch_size=5

  0% 0/1 [00:00<?, ?it/s]src.shape torch.Size([1, 3, 2048]) target.shape torch.Size([1, 3, 2048])
100% 1/1 [00:00<00:00,  2.11it/s]


#可视化粗配准结果
- <font color='red'>红色</font>为源点云
- <font color='blue'>蓝色</font>为目标点云
- <font color='green'>绿色</font>为粗配准结果

In [7]:
src=np.load('transformed_data/1.npy')
tgt=np.load('transformed_data/2.npy')
new_tgt=np.load('new_1.npy')


fig=go.Figure(data=[go.Scatter3d(
        x=src[:,0],
        y=src[:,1],
        z=src[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='red',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=tgt[:,0],
        y=tgt[:,1],
        z=tgt[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='blue',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=new_tgt[:,0],
        y=new_tgt[:,1],
        z=new_tgt[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='green',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    )
    ])
    #new_data = generate_dataset(origin_data)
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))
fig.show()

#利用go-icp对粗配准结果进行精配准
icp.py有三个命令行参数:
- --src:源点云
- --tgt:目标点云
- --name:配准结果文件的名称

In [8]:
!python go-icp_cython/icp.py --src=/content/transformed_data/1.npy --tgt=/content/new_1.npy --name=12

Building Distance Transform...
REGISTERING....
INITIALIZE THE GOICP SYSTEM :: 
FINDING OUTERBNB :: 
Error*: 11.6072 (Init)
Error*: 2.31796 (ICP 0.033284s)
ICP-ONLY Rotation Matrix:
   0.9611199    0.2633424    0.0830615 
  -0.2469458    0.9543236   -0.1681783 
  -0.1235560    0.1411279    0.9822509 
ICP-ONLY Translation Vector:
  -0.0129046 
  -0.0215237 
   0.0292783 
LB=0.110001  L=3
Error*: 2.31796, LB: 0.275396, epsilon: 2.048
CLEARING THE GOICP SYSTEM :: 
TOTAL TIME :  58.325648069381714
(2048, 3) (2048, 1)
[[ 0.96111992  0.26334239  0.08306148]
 [-0.24694584  0.9543236  -0.16817831]
 [-0.12355604  0.14112787  0.9822509 ]]
[-0.01290457 -0.02152375  0.02927831  1.        ]
[[ 0.96111992  0.26334239  0.08306148 -0.01290457]
 [-0.24694584  0.9543236  -0.16817831 -0.02152375]
 [-0.12355604  0.14112787  0.9822509   0.02927831]
 [ 0.          0.          0.          1.        ]]


#精确配准结果展示

In [9]:
from plyfile import PlyData,PlyElement

xyz=np.load('indermidiate_data/12.npy')

figure=go.Figure(data=[go.Scatter3d(        
        x=src[:,0],
        y=src[:,1],
        z=src[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='red',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=xyz[:,0],
        y=xyz[:,1],
        z=xyz[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='green',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    )                   
])
figure.update_layout(margin=dict(l=0, r=0, b=0, t=0))
figure.show()

#直接使用go-icp进行配准

In [13]:
!python go-icp_cython/icp.py --src=/content/transformed_data/1.npy --tgt=/content/transformed_data/2.npy --name=12_icp

Building Distance Transform...
REGISTERING....
INITIALIZE THE GOICP SYSTEM :: 
FINDING OUTERBNB :: 
Error*: 63.3217 (Init)
Error*: 2.31787 (ICP 0.04857s)
ICP-ONLY Rotation Matrix:
   0.7410413    0.6482037    0.1751849 
  -0.4838743    0.6964098   -0.5299801 
  -0.4655356    0.3079697    0.8297176 
ICP-ONLY Translation Vector:
  -0.0163277 
   0.0043680 
  -0.0244464 
Error*: 2.31787, LB: 0.280157, epsilon: 2.048
CLEARING THE GOICP SYSTEM :: 
TOTAL TIME :  23.264325380325317
(2048, 3) (2048, 1)
[[ 0.74104127  0.64820372  0.17518488]
 [-0.48387434  0.69640978 -0.52998013]
 [-0.46553559  0.3079697   0.82971759]]
[-0.01632766  0.00436801 -0.02444637  1.        ]
[[ 0.74104127  0.64820372  0.17518488 -0.01632766]
 [-0.48387434  0.69640978 -0.52998013  0.00436801]
 [-0.46553559  0.3079697   0.82971759 -0.02444637]
 [ 0.          0.          0.          1.        ]]


#二叉树归并配准8个视角

In [17]:
!python test.py --exp_name=dcp_v2 --model=dcp --emb_nn=pointnet --pointer=transformer --head=svd --eval --model_path=model.best.t7 --src=transformed_data/3.npy --target=transformed_data/4.npy --batch_size=5
!python go-icp_cython/icp.py --src=./transformed_data/3.npy --tgt=./new_3.npy --name=34
!python test.py --exp_name=dcp_v2 --model=dcp --emb_nn=pointnet --pointer=transformer --head=svd --eval --model_path=model.best.t7 --src=transformed_data/5.npy --target=transformed_data/6.npy --batch_size=5
!python go-icp_cython/icp.py --src=./transformed_data/5.npy --tgt=./new_5.npy --name=56
!python test.py --exp_name=dcp_v2 --model=dcp --emb_nn=pointnet --pointer=transformer --head=svd --eval --model_path=model.best.t7 --src=transformed_data/7.npy --target=transformed_data/8.npy --batch_size=5
!python go-icp_cython/icp.py --src=/content/transformed_data/7.npy --tgt=./new_7.npy --name=78

  0% 0/1 [00:00<?, ?it/s]src.shape torch.Size([1, 3, 2048]) target.shape torch.Size([1, 3, 2048])
100% 1/1 [00:00<00:00, 25.50it/s]
Building Distance Transform...
REGISTERING....
INITIALIZE THE GOICP SYSTEM :: 
FINDING OUTERBNB :: 
Error*: 45.0634 (Init)
Error*: 38.2078 (ICP 0.090229s)
ICP-ONLY Rotation Matrix:
   0.9632918   -0.0069122   -0.2683669 
   0.0184272    0.9990131    0.0404122 
   0.2678225   -0.0438739    0.9624687 
ICP-ONLY Translation Vector:
  -0.0800983 
   0.0019237 
  -0.0045211 
Error*: 15.5421
Error*: 11.8959(ICP 0.046374s)
Error*: 11.0269
Error*: 2.03965(ICP 0.024547s)
Error*: 2.03965, LB: 0, epsilon: 2.048
CLEARING THE GOICP SYSTEM :: 
TOTAL TIME :  18.81094765663147
(2048, 3) (2048, 1)
[[-0.70393086  0.70765191  0.06090909]
 [ 0.69236159  0.7027909  -0.16346437]
 [-0.15848205 -0.07289662 -0.98466719]]
[ 0.09390072 -0.07417359 -0.16287761  1.        ]
[[-0.70393086  0.70765191  0.06090909  0.09390072]
 [ 0.69236159  0.7027909  -0.16346437 -0.07417359]
 [-0.158482

In [21]:
!python test.py --exp_name=dcp_v2 --model=dcp --emb_nn=pointnet --pointer=transformer --head=svd --eval --model_path=model.best.t7 --src=indermidiate_data/12.npy --target=indermidiate_data/34.npy --batch_size=5
!python go-icp_cython/icp.py --src=indermidiate_data/12.npy --tgt=./new_12.npy --name=1234
!python test.py --exp_name=dcp_v2 --model=dcp --emb_nn=pointnet --pointer=transformer --head=svd --eval --model_path=model.best.t7 --src=indermidiate_data/56.npy --target=indermidiate_data/78.npy --batch_size=5
!python go-icp_cython/icp.py --src=indermidiate_data/56.npy --tgt=./new_56.npy --name=5678

  0% 0/1 [00:00<?, ?it/s]src.shape torch.Size([1, 3, 2048]) target.shape torch.Size([1, 3, 2048])
100% 1/1 [00:00<00:00, 25.20it/s]
Building Distance Transform...
REGISTERING....
INITIALIZE THE GOICP SYSTEM :: 
FINDING OUTERBNB :: 
Error*: 29.1214 (Init)
Error*: 8.99364 (ICP 0.070645s)
ICP-ONLY Rotation Matrix:
   0.6759965    0.3975718    0.6204556 
  -0.4892988    0.8717430   -0.0254903 
  -0.5510124   -0.2863570    0.7838271 
ICP-ONLY Translation Vector:
  -0.0042709 
   0.0309352 
   0.0090392 
Error*: 3.59254
Error*: 1.59428(ICP 0.017098s)
Error*: 1.59428, LB: 7.9265e-05, epsilon: 2.048
CLEARING THE GOICP SYSTEM :: 
TOTAL TIME :  24.30180048942566
(2048, 3) (2048, 1)
[[-0.01049228 -0.94955108 -0.31343708]
 [-0.78642209  0.20143625 -0.58392101]
 [ 0.61760042  0.24036711 -0.74886144]]
[-0.05695732 -0.00262571  0.10783145  1.        ]
[[-0.01049228 -0.94955108 -0.31343708 -0.05695732]
 [-0.78642209  0.20143625 -0.58392101 -0.00262571]
 [ 0.61760042  0.24036711 -0.74886144  0.10783145

In [23]:
!python test.py --exp_name=dcp_v2 --model=dcp --emb_nn=pointnet --pointer=transformer --head=svd --eval --model_path=model.best.t7 --src=indermidiate_data/1234.npy --target=indermidiate_data/5678.npy --batch_size=5
!python go-icp_cython/icp.py --src=indermidiate_data/1234.npy --tgt=./new_1234.npy --name=new

  0% 0/1 [00:00<?, ?it/s]src.shape torch.Size([1, 3, 2048]) target.shape torch.Size([1, 3, 2048])
100% 1/1 [00:00<00:00, 25.41it/s]
Building Distance Transform...
REGISTERING....
INITIALIZE THE GOICP SYSTEM :: 
FINDING OUTERBNB :: 
Error*: 21.6555 (Init)
Error*: 10.9009 (ICP 0.030905s)
ICP-ONLY Rotation Matrix:
   0.9689354   -0.0677610    0.2378501 
   0.1107763    0.9787730   -0.1724293 
  -0.2211173    0.1934210    0.9558742 
ICP-ONLY Translation Vector:
   0.0134544 
   0.0439416 
  -0.0232977 
Error*: 10.8737
Error*: 0.4176(ICP 0.019876s)
Error*: 0.4176, LB: 0, epsilon: 2.048
CLEARING THE GOICP SYSTEM :: 
TOTAL TIME :  19.700453519821167
(2048, 3) (2048, 1)
[[-0.08317381 -0.21856967  0.97227016]
 [-0.29603762  0.93702556  0.18532198]
 [-0.9515481  -0.2724147  -0.14264089]]
[-0.09477681 -0.01240418  0.01120388  1.        ]
[[-0.08317381 -0.21856967  0.97227016 -0.09477681]
 [-0.29603762  0.93702556  0.18532198 -0.01240418]
 [-0.9515481  -0.2724147  -0.14264089  0.01120388]
 [ 0.   

In [25]:
!python test.py --exp_name=dcp_v2 --model=dcp --emb_nn=pointnet --pointer=transformer --head=svd --eval --model_path=model.best.t7 --src=./b.npy --target=indermidiate_data/new.npy --batch_size=5
!python go-icp_cython/icp.py --src=./b.npy --tgt=./new_b.npy --name=result

  0% 0/1 [00:00<?, ?it/s]src.shape torch.Size([1, 3, 2048]) target.shape torch.Size([1, 3, 2048])
100% 1/1 [00:00<00:00, 25.38it/s]
Building Distance Transform...
REGISTERING....
INITIALIZE THE GOICP SYSTEM :: 
FINDING OUTERBNB :: 
Error*: 50.8882 (Init)
Error*: 36.3143 (ICP 0.025904s)
ICP-ONLY Rotation Matrix:
   0.9936611    0.1099805    0.0232800 
  -0.1024566    0.9712085   -0.2150722 
  -0.0462635    0.2113237    0.9763206 
ICP-ONLY Translation Vector:
  -0.0469815 
  -0.1258285 
  -0.0599777 
Error*: 31.7389
Error*: 8.14965(ICP 0.056442s)
Error*: 3.93099
Error*: 0.227343(ICP 0.007399s)
Error*: 0.227343, LB: 0, epsilon: 2.048
CLEARING THE GOICP SYSTEM :: 
TOTAL TIME :  19.764626264572144
(2048, 3) (2048, 1)
[[ 0.09512576 -0.2702784  -0.95807142]
 [ 0.05287439 -0.95970517  0.27598914]
 [-0.99406014 -0.0769111  -0.07700175]]
[ 0.04372274 -0.03678159  0.03428063  1.        ]
[[ 0.09512576 -0.2702784  -0.95807142  0.04372274]
 [ 0.05287439 -0.95970517  0.27598914 -0.03678159]
 [-0.994

#单视角直接icp配准结果

In [26]:
!python go-icp_cython/icp.py --src=/content/b.npy --tgt=/content/transformed_data/1.npy --name=1a_icp

Building Distance Transform...
REGISTERING....
INITIALIZE THE GOICP SYSTEM :: 
FINDING OUTERBNB :: 
Error*: 48.287 (Init)
Error*: 18.5359 (ICP 0.017425s)
ICP-ONLY Rotation Matrix:
   0.8490775    0.5265056    0.0431192 
  -0.5247946    0.8500248   -0.0452589 
  -0.0604814    0.0157996    0.9980443 
ICP-ONLY Translation Vector:
  -0.0278304 
  -0.1182223 
  -0.0072095 
Error*: 8.51044
Error*: 7.42409(ICP 0.027226s)
Error*: 5.76111
Error*: 3.77119(ICP 0.014531s)
LB=1.111831  L=4
LB=1.633669  L=3
Error*: 3.77119, LB: 1.725, epsilon: 2.048
CLEARING THE GOICP SYSTEM :: 
TOTAL TIME :  207.6855607032776
(2048, 3) (2048, 1)
[[ 0.10804475  0.01934668 -0.99395777]
 [ 0.38662213 -0.92192357  0.02408184]
 [-0.91588733 -0.38688808 -0.10708888]]
[ 0.07272189 -0.12399333 -0.04314299  1.        ]
[[ 0.10804475  0.01934668 -0.99395777  0.07272189]
 [ 0.38662213 -0.92192357  0.02408184 -0.12399333]
 [-0.91588733 -0.38688808 -0.10708888 -0.04314299]
 [ 0.          0.          0.          1.        ]]


In [14]:
from plyfile import PlyData,PlyElement

xyz1=np.load('indermidiate_data/1a_icp.npy')
src=np.load('b.npy')
figure1=go.Figure(data=[go.Scatter3d(        
        x=src[:,0],
        y=src[:,1],
        z=src[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='red',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=xyz1[:,0],
        y=xyz1[:,1],
        z=xyz1[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='green',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    )                   
])
figure1.update_layout(margin=dict(l=0, r=0, b=0, t=0))
figure1.show()

#最终配准结果

In [29]:
from plyfile import PlyData,PlyElement

src=np.load('b.npy')
xyz1=np.load('indermidiate_data/result.npy')

figure1=go.Figure(data=[go.Scatter3d(        
        x=src[:,0],
        y=src[:,1],
        z=src[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='red',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    ),
    go.Scatter3d(
        x=xyz1[:,0],
        y=xyz1[:,1],
        z=xyz1[:,2],
        mode='markers',
        name='data',
        marker=dict(
        size=1,      
        color='green',          # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
    )                   
])
figure1.update_layout(margin=dict(l=0, r=0, b=0, t=0))
figure1.show()